#!/bin/bash

set -x

JOBID=$1
CONFIGFILE=$2

if [ -z "${JOBID}" -o -z "${CONFIGFILE}" ]; then
	echo "Need jobid and config file"
	exit 1
fi
if [ ! -s "${CONFIGFILE}" ]; then
	echo "Config file does not exist or is empty"
	exit 1
fi

BASE=$(readlink -f $(dirname $(readlink -f $0))/..)
HOSTNAME=$(hostname)
TREECACHE=${BASE}/treecache

. ${BASE}/config/buildhost-default 
if [ -f ${BASE}/config/buildhost-${HOSTNAME} ]; then
	. ${BASE}/config/buildhost-${HOSTNAME}
fi

updatetree() {

	# Get tree from config file and make it fs flat
	# for example
	#
	# git://git.kernel.org/pub/scm/linux/kernel/git/mips/linux.git
	# git---git-kernel-org-pub-scm-linux-kernel-git-mips-linux-git
	#
	# and then update the tree by pulling if it exists or clone it
	# 
	GITTREE=$(jq -r .gittree <${CONFIGFILE})
	TREENAME=$(echo -n ${GITTREE} | tr -c 'a-z' '-')

	if [ ! -d ${TREECACHE}/${TREENAME} ]; then
		git clone ${GITTREE} ${TREECACHE}/${TREENAME} \
			2>&1 | tee -a ${BASE}/output/${JOBID}.log
	else
		pushd ${TREECACHE}/${TREENAME}
		git pull 2>&1 | tee -a ${BASE}/output/${JOBID}.log
		popd
	fi
}

rundocker() {

	time docker run \
			--rm \
			-it \
			-v ${BASE}/treecache:/treecache \
			-v ${BASE}/config:/config \
			-v ${BASE}/output:/output \
			-v ${BASE}/scripts:/scripts \
			-e TREECACHEDIR=/treecache \
			-e OUTPUTDIR=/output \
			-e BUILDHOST=$(hostname) \
			-e JOBID=${JOBID} \
			bbb/buster \
			/scripts/buildindocker \
		2>&1 | tee -a ${BASE}/output/${JOBID}.log
}

[ -d ${BASE}/output ] || mkdir -p ${BASE}/output
[ -d ${BASE}/treecache ] || mkdir -p ${BASE}/treecache
[ -d ${BASE}/config/build ] || mkdir -p ${BASE}/config/build

cp ${CONFIGFILE} ${BASE}/config/build/${JOBID}

updatetree
rundocker
